services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
